text1 = (input("Text1:  "))
text2 = (input("Text2:   "))
print("Concatenated text:  ", text1, text2 )
print("------"*10)
print('_-_-_-'*5,text1*2,'_-_-_-'*5)
a, b, c = (input('A')),(input('B')),(input('C'))
print(a+" "+b+" "+c)
print("_-_-_-_-_-"*10)
print("You wrote, ", input("_insert some text_,"), ", text")